# Tool integrations that must be *sourced* — a prompt hook, widget or keybinding.
# Anything that merely prints a #compdef script belongs in `mise run
# shell:completions`, which writes it to fpath for zsh to autoload on first use.
#
# Runs after 30_mise.zsh so $+commands sees mise-managed tools, and after
# 20_zim.zsh for _evalcache and zsh-defer. starship must render before the first
# prompt, so it is not deferred.
(($+commands[zoxide]  )) && zsh-defer _evalcache zoxide init zsh
(($+commands[starship])) && _evalcache starship init zsh
(($+commands[tv]      )) && zsh-defer _evalcache tv init zsh

# fzf's completion half, generated by shell:completions.
[[ -r $ZDOTDIR/fzf-completion.zsh ]] && zsh-defer source $ZDOTDIR/fzf-completion.zsh

# Google Cloud SDK — installed under XDG_DATA_HOME rather than $HOME.
# Appended, not prepended: this runs after mise activation, so a prepend would
# rank gcloud's bin above every mise tool (`mise doctor` warns), and a gcloud
# component such as kubectl would silently shadow the mise one.
if [[ -d "$XDG_DATA_HOME/google-cloud-sdk" ]]; then
  path+=("$XDG_DATA_HOME/google-cloud-sdk/bin")

  # gcloud needs its own interpreter and uv owns every python here. Resolve the
  # newest uv-managed one by glob rather than pinning a version and platform
  # triple: the old literal cpython-3.14-macos-aarch64-none path broke the moment
  # uv bumped python, and named a directory no Linux machine has.
  # (Nn[-1]) = null-glob, numeric sort, last match.
  () {
    local py=( $XDG_DATA_HOME/uv/python/cpython-[0-9]*/bin/python3(Nn[-1]) )
    (( $#py )) && export CLOUDSDK_PYTHON=$py[1]
  }

  zsh-defer source "$XDG_DATA_HOME/google-cloud-sdk/completion.zsh.inc"
fi
