# Tool integrations that must be *sourced* — a prompt hook, widget or keybinding.
# Anything that merely prints a #compdef script belongs in `mise run
# shell:completions`, which writes it to fpath for zsh to autoload on first use.
#
# Runs after 30_mise.zsh so $+commands sees mise-managed tools, and after
# 20_zim.zsh for _evalcache and zsh-defer. starship must render before the first
# prompt, so it is not deferred.
(($+commands[zoxide]  )) && zsh-defer _evalcache zoxide init zsh
(($+commands[starship])) && _evalcache starship init zsh
(($+commands[tv]      )) && zsh-defer _evalcache tv init zsh

# fzf's completion half, generated by shell:completions.
[[ -r $ZDOTDIR/fzf-completion.zsh ]] && zsh-defer source $ZDOTDIR/fzf-completion.zsh

# Google Cloud SDK — installed under XDG_DATA_HOME rather than $HOME.
if [[ -d "$XDG_DATA_HOME/google-cloud-sdk" ]]; then
  path=("$XDG_DATA_HOME/google-cloud-sdk/bin" $path)
  zsh-defer source "$XDG_DATA_HOME/google-cloud-sdk/completion.zsh.inc"
fi
