style_edition = "2024"
version = "Two"
use_small_heuristics = "Max"
fn_params_layout = "Vertical"
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"
# This file should exist even if empty, to stop a spurious config file from being picked up in the parent.
newline_style = "Unix"

comment_width = 100
wrap_comments = true

# Use unstable features
unstable_features = true

group_imports = "StdExternalCrate"
max_width = 100

## Visually align, useful in writing the view
# indent_style = "Block"
# imports_indent = "Block"
reorder_imports = true
reorder_impl_items = true
imports_granularity = "One"
## I want to be able to delete unused imports easily
imports_layout = "Vertical"
## Default value is false, yet clipy keeps nagging on this
use_field_init_shorthand = true
## also format macro
format_macro_matchers = true
force_multiline_blocks = true
format_code_in_doc_comments = true
