[1]
monitor = "specific"
monitorName = "LG Ultra HD"
monitorDisplayId = 2
monitorAnchorX = 0.0
monitorAnchorY = 1080.0

[2]
monitor = "specific"
monitorName = "LG Ultra HD"
monitorDisplayId = 2
monitorAnchorX = 0.0
monitorAnchorY = 1080.0

[3]
monitor = "specific"
monitorName = "LG Ultra HD"
monitorDisplayId = 2
monitorAnchorX = 0.0
monitorAnchorY = 1080.0

[4]
monitor = "specific"
monitorName = "LG Ultra HD"
monitorDisplayId = 2
monitorAnchorX = 0.0
monitorAnchorY = 1080.0
