# To get a full list of supported fonts use the `kitty +list-fonts` command.
# font_family FantasqueSansM Nerd Font Mono
font_size 24
map ctrl+0 change_font_size all 0
map ctrl+equal   change_font_size all +2.0
map ctrl+minus       change_font_size all -2.0

# Chinese / Japanese / Korean fallback font
# Chinese + CJK punctuation
symbol_map U+3000-U+303F,U+3400-U+4DBF,U+4E00-U+9FFF,U+F900-U+FAFF Hannotate SC

# Japanese kana
symbol_map U+3040-U+309F,U+30A0-U+30FF Hiragino Sans

# Korean Hangul
symbol_map U+1100-U+11FF,U+3130-U+318F,U+AC00-U+D7AF Apple SD Gothic Neo

# Fullwidth forms, common in CJK text
# symbol_map U+FF00-U+FFEF Noto Sans CJK SC
symbol_map U+FF00-U+FFEF Hannotate SC
